spring.application.name=gateway-merezh
server.port=8000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet=DEBUG

jwt.secret=yXLvsG1Qq8ZkzAiO5xDQY4oR8TqmF0DgswZjSnORre4=
jwt.token.expiration.access=1800
jwt.token.expiration.refresh=604800

service.users.url=http://userservice-merezh:8080
service.users.path=/api/v1/users

service.auth.url=http://authservice-merezh:8081
service.auth.path=/api/v1/auth

service.wallets.url=http://walletservice-merezh:8083
service.wallets.path=/api/v1/wallets

service.orders.url=http://orderservice-merezh:8085
service.orders.path=/api/v1/orders

service.payments.url=http://paymentservice-merezh:8084
service.payments.path=/api/v1/payments